eggItem:
  block: PLAYER_HEAD
  displayName: "#BA77CCEaster Egg&f Block &7(Place)"
  lore:
    - ""
    - "&7Place to create a new Egg!"
  texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjU2ZjdmM2YzNTM2NTA2NjI2ZDVmMzViNDVkN2ZkZjJkOGFhYjI2MDA4NDU2NjU5ZWZlYjkxZTRjM2E5YzUifX19

settings:
  autosave: 100 #20 = 1 second // 100 = 5 seconds

  defaultActions:
    - "msg: &eYou have found an Easter Egg!"
    - "cmd: give %player% minecraft:diamond 1"

  foundAllEggsActions:
    - "msg: &eYou found all Easter Eggs!"

  randomEggTextures:
    - eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjU2ZjdmM2YzNTM2NTA2NjI2ZDVmMzViNDVkN2ZkZjJkOGFhYjI2MDA4NDU2NjU5ZWZlYjkxZTRjM2E5YzUifX19
    - eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNThiOWUyOWFiMWE3OTVlMmI4ODdmYWYxYjFhMzEwMjVlN2NjMzA3MzMzMGFmZWMzNzUzOTNiNDVmYTMzNWQxIn19fQ==
    - eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTViOGRjYmVhMjdmNDJmNWFlOTEwNDQ1ZTA1ZGFjODlkMzEwYWFmMjM2YTZjMjEyM2I4NTI4MTIwIn19fQ==
    - eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTg4OWYxMWM4ODM4YzA5ZTFlY2YyZjgzNDM5ZWJjYjlmMzI0ZTU2N2IwZTlkYzRiN2MyNWQ5M2U1MGZmMmIifX19
    - eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjNkNjliMjNhZTU5MmM2NDdlYjhkY2ViOWRhYWNlNDQxMzlmNzQ4ZTczNGRjODQ5NjI2MTNjMzY2YTA4YiJ9fX0=
    - eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzc2NTk1ZWZmY2M1NjI3ZTg1YjE0YzljODgyNDY3MWI1ZWMyOTY1NjU5YzhjNDE3ODQ5YTY2Nzg3OGZhNDkwIn19fQ==
    - eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjY0NDMwZTQ5M2ZlYjVlYWExNDU1ODJlNTRlNzYxYTg2MDNmYjE2Y2MwZmYxMjY4YTVkMWU4NjRlNmY0NzlmNiJ9fX0=

  particles:
    notFound:
      enabled: true
      type: VILLAGER_HAPPY
      count: 7
      cooldown: 20
      maxDistance: 0
    alreadyFound:
      enabled: true
      type: VILLAGER_ANGRY
      count: 7

  sounds:
    notFound:
      enabled: true
      type: UI_TOAST_CHALLENGE_COMPLETE
      pitch: 2
      volume: 10
    alreadyFound:
      enabled: true
      type: ENTITY_VILLAGER_NO
      pitch: 1
      volume: 10

  permissions:
    eggBreak: eastereggs.break
    eggPlace: eastereggs.place
    eggList: eastereggs.list
    eggTp: eastereggs.tp
    eggFound: eastereggs.found
    createEgg: eastereggs.create
    editEgg: eastereggs.edit
    giveEgg: eastereggs.give
    setEgg: eastereggs.set
    reload: eastereggs.reload
    menu: eastereggs.menu

  cancellationWords:
    - "cancel"
    - "stop"

  titles:
    eggFound:
      title: "&e&lEASTER EGGS"
      subtitle: "&fYou found an easter egg! &7(%found%/%total%)"
      fadeIn: 0
      stay: 50
      fadeOut: 0

  animation:
    enabled: true
    material: PLAYER_HEAD
    texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjU2ZjdmM2YzNTM2NTA2NjI2ZDVmMzViNDVkN2ZkZjJkOGFhYjI2MDA4NDU2NjU5ZWZlYjkxZTRjM2E5YzUifX19

  firework:
    enabled: true
    power: 0

inventories:
  main:
    title: "&d&lEE &8| Eggs List (Page %page%)"
    size: 45
    items:
      prevPage:
        material: ARROW
        name: "&ePrevious Page"
        slot: 39
      nextPage:
        material: ARROW
        name: "&eNext Page"
        slot: 41
      close:
        material: IRON_DOOR
        name: "&cClose"
        slot: 40
      border:
        material: BLACK_STAINED_GLASS_PANE
        name: "&f "
        slots:
          - 0
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 36
          - 37
          - 38
          - 42
          - 43
          - 44
      eggs:
        material: PAPER
        name: "&dEaster Egg &7#%id%"
        slots:
          - 9
          - 10
          - 11
          - 12
          - 13
          - 14
          - 15
          - 16
          - 17
          - 18
          - 19
          - 20
          - 21
          - 22
          - 23
          - 24
          - 25
          - 26
          - 27
          - 28
          - 29
          - 30
          - 31
          - 32
          - 33
          - 34
          - 35
  editor:
    title: "&d&lEE &8| Egg Editor (ID #%id%)"
    size: 45
    items:
      teleport:
        material: ENDER_PEARL
        name: "&eTeleport to the Egg"
        slot: 22
      delete:
        material: BARRIER
        name: "&cDelete to the Egg"
        slot: 24
      back:
        material: OAK_DOOR
        name: "&eBack"
        slot: 40
      actions:
        material: PAPER
        name: "&eActions 1"
        lore:
          - ""
          - "&7Click to open"
        slot: 20
      border:
        material: BLACK_STAINED_GLASS_PANE
        slots:
          - 0
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 36
          - 37
          - 38
          - 39
          - 41
          - 42
          - 43
          - 44
  actionslist:
    title: "&d&lEE &8| Actions List (Page %page%)"
    size: 45
    items:
      actions:
        command:
          name: "&eAction %id% &7(Command)"
          material: COMMAND_BLOCK
          lore:
            - "&f"
            - "&7Command: &e%string%"
        message:
          name: "&eAction %id% &7(Message)"
          material: PAPER
          lore:
            - "&f"
            - "&7Message: &e%string%"
        slots:
          - 9
          - 10
          - 11
          - 12
          - 13
          - 14
          - 15
          - 16
          - 17
          - 18
          - 19
          - 20
          - 21
          - 22
          - 23
          - 24
          - 25
          - 26
          - 27
          - 28
          - 29
          - 30
          - 31
          - 32
          - 33
          - 34
          - 35
      commandAction:
        material: ORANGE_STAINED_GLASS_PANE
        name: "&eAdd Command Action"
        slot: 43
      messageAction:
        material: WHITE_STAINED_GLASS_PANE
        name: "&eAdd Message Action"
        slot: 44
      prevPage:
        material: ARROW
        name: "&ePrevious Page"
        slot: 39
      nextPage:
        material: ARROW
        name: "&eNext Page"
        slot: 41
      back:
        material: OAK_DOOR
        name: "&eBack"
        slot: 40
      border:
        material: BLACK_STAINED_GLASS_PANE
        name: "&f "
        slots:
          - 0
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 36
          - 37
          - 38
          - 42

messages:
  list:
    syntaxe: "&d#%id% &7- "
    teleport: "&f[Teleport]"
    teleportClick: "&eClick to teleport"
    edit: "&e[Edit]"
    editClick: "&eClick to edit"
    footer:
      prevArrow: "&7<<< "
      prevPageHover: "&eClick to open"
      noPrevArrow: "&8<<< "
      noPrevPageHover: "&7No previous page"
      nextArrow: " &7>>>"
      nextPageHover: "&eClick to open"
      noNextArrow: " &8>>>"
      noNextPageHover: "&7No next page"
      pageInfo: "&7(%current%/%max%)"
      pageInfoHover: "&fTotal eggs amount: &e%total%"

  usage:
    syntaxe: "&cInvalid Command Usage! &7Usage: &f/ee %arguments%"
    argument: "<%arg%>"
  help:
    - ""
    - "&f                    &d&lEASTER EGGS"
    - ""
    - "&d  ▉▉▉     &d→ &f/ee give &7- Gives you the Easter Egg block"
    - "&d ▉▉▉▉    &d→ &f/ee menu &7- Opens the Easter Eggs Menu"
    - "&d ▉▉▉▉    &d→ &f/ee reload &7- Reloads the plugin"
    - "&d▉&b▉&d▉&3▉&d▉   &d→ &f/ee create &7- Creates an Egg from holding Block"
    - "&3▉&d▉&b▉&d▉&b▉   &d→ &f/ee set &7- Sets an Easter Egg to looking Block"
    - "&d▉▉▉▉▉   &d→ &f/ee list &7- A list of all Easter Eggs"
    - "&d ▉▉▉▉    &d→ &f/ee found &7- An amount of found Easter Eggs"
    - ""
    - "&f &7&oMade by MrLarkyy_"
    - ""
  reload: "&ePlugin has been reloaded!"
  noPermission: "&cYou have no permission to do that!"
  noEggs: "&cNo eggs found..."
  found: "&cYou have already found this Easter Egg!"
  foundAmount: "&eYou have found &6%found%/%total%&e Easter Eggs!"
  eggBreak: "&eYou just &6Broke &ethe Easter Egg!"
  eggPlace: "&dYou just placed a new Easter Egg!"
  eggGive: "&eYou have been given the Easter Egg block!"
  eggRemoved: "&cYou just &4Removed&c the Easter Egg!"
  teleported: "&eYou have been teleported to the Egg!"
  mustBeNumber: "&cYou must type a number!"
  invalidID: "&cThere is no Easter Egg with this ID!"
  actionRemoved: "&cYou just &4Removed&c the action!"
  actionAdded: "&eYou have added a new action!"
  actionCancelled: "&cYou have &4Cancelled&c adding the action!"
  typeAction: "&7Type the action into the chat please...\n&7Type &ocancel&7 to cancel the action."
  onlyPlayer: "&cThis command can be sent only ingame!"
  noBlockInHand: "&cYou are not holding any block!"
  eggBlockCreated: "&eYou have created the Easter Egg Block!"
  eggBlockSet: "&eYou have set an Easter Egg to the looked block!"
  mustLookAtBlock: "&cYou are not looking at block!"
  alreadyEditing: "&cYou are editing an Easter Egg right now!\n&cType &4cancel&c to cancel the action..."