name: Leastereggs
version: ${project.version}
main: cz.larkyy.leastereggs.Leastereggs
softdepend:
  - MultiverseCore
  - SuperiorSkyblock2
  - HeadDatabase
  - PlaceholderAPI
api-version: 1.13
commands:
  leastereggs:
    aliases: [ee,eastergg,eastereggs]
    description: lEasterEggs
